global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'users-service'
    static_configs:
      - targets: ['host.docker.internal:4000']

  - job_name: 'content-service'
    static_configs:
      - targets: ['host.docker.internal:4001']
