global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'users-service'
    static_configs:
      - targets: ['listeners-service.railway.internal:4000']

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service.railway.internal:4001']
